ALTER TABLE USERS
ADD COLUMN payment_status VARCHAR(20) DEFAULT 'NOTSTARTED' NOT NULL,
ADD COLUMN payment_expiration_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN first_payment_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN last_payment_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;